# Generated by Django 4.1.7 on 2024-02-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item',
            new_name='menu_item_description',
        ),
    ]
